name: MlOps CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Upgrade pip and build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Start MLflow Server
        run: |
          mlflow server \
          --backend-store-uri sqlite:///mlflow.db \
          --default-artifact-root ./mlartifacts \
          --host 0.0.0.0 --port 5000 &
          sleep 10
          curl --retry 5 --retry-delay 2 http://localhost:5000

      - name: Run Data Processing
        run: |
          python src/data/run_processing.py \
           --input data/raw/house_data.csv  \
           --output data/processed/cleaned_house_data.csv

      - name: Run Feature Engineering
        run: |
          python src/features/engineer.py \
           --input data/processed/cleaned_house_data.csv \
           --output data/processed/featured_house_data.csv \
           --preprocessor models/trained/preprocessor.pkl

      - name: Run Model Training
        run: |
          python src/models/train_model.py \
           --config configs/model_config.yaml \
           --data data/processed/featured_house_data.csv \
           --models-dir models/trained \
           --mlflow-tracking-uri http://localhost:5000

      - name: stop MLflow Server
        run: |
          pkill -f "mlflow server"
          sleep 10

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: set docker buildx context
        uses: docker/setup-buildx-action@v3

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          tags: kirasama/fastapi:${{ github.sha }}
          push: true





      
